%%writefile wrangler.toml
name = "api"
main = "src/index.js"
compatibility_date = "2024-12-12"
account_id = "4ab2ec221eb0631878fd0d13697a9fc5"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "xizoa_d1"
# ðŸ‘‡ YAHAN APNI NAYI ID PASTE KARNA (Jo Step 1 ya 2 se mili)
database_id = "YAHAN_NAYI_ID_DALO"

[vars]
API_URL = "https://api.xizoa.com"
APP_URL = "https://app.xizoa.com"