name = "xizoa-api"
main = "src/index.js"
compatibility_date = "2024-12-12"

# Cloudflare Dashboard के URL में देखिए, वहां account_id मिल जाएगा
account_id = "APNA_ACCOUNT_ID_YAHAN_DAALEIN"
workers_dev = true

# Database Connection (ID maine aapke screenshot se le li hai)
[[d1_databases]]
binding = "DB"
database_name = "xizoa_d1"
database_id = "7e9daa64-7d20-4100-87bc-52080f3607c8"

[vars]
API_URL = "https://xizoa-api.priyanshumaurya758.workers.dev"
APP_URL = "https://app.xizoa.com"
